openapi: 3.0.1
info:
  title: enty API
  description: '...'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: ''
tags:
  - name: mind
    description: ''
  - name: edstorage
    description: ''

paths:
  /mind/wish:
    post:
      parameters:
        - name: offset
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wishString:
                  type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  eids:
                    type: array
                    items:
                      type: string
                      format: uuid
                  total:
                    type: integer

  /edstorage/{eid}:
    get:
      responses:
        200:
          description: ''
          headers:
            Content-Type: {}
