name: Docker Images CI

on:
  push:
    branches: [ main ]

jobs:

  build-push-mind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Docker build and push"
      uses: docker/build-push-action@v2
      with:
        file: ./src/enty.Mind.Server/Dockerfile
        context: .
        push: true
        tags: prunkles/enty:mind-latest

  build-push-storage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: "Docker build and push"
      uses: docker/build-push-action@v2
      with:
        file: ./src/enty.ResourceStorage.Server/Dockerfile
        context: .
        push: true
        tags: prunkles/enty:storage-latest

  build-push-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Docker build and push"
      uses: docker/build-push-action@v2
      with:
        file: ./src/Web/Dockerfile
        context: .
        push: true
        tags: prunkles/enty:webapp-latest
